const mockAddress = [
  {
    firstName: 'Alex',
    lastName: 'Abe',
    gender: 'M',
    address: {
      type: 'apt',
      houseNumber: '123',
      street: '5th Ave',
      city: 'New York',
      state: 'NY',
      zipcode: '10003',
    },
    phoneNumber: '2129089900',
  },
  {
    firstName: 'Alex',
    lastName: 'Jackson',
    gender: 'M',
    address: {
      type: 'apt',
      houseNumber: '8876',
      street: '88th Ave',
      city: 'Jackson Heights',
      state: 'NY',
      zipcode: '11372',
    },
    phoneNumber: '7188986754',
  },
  {
    firstName: 'Allan',
    lastName: 'Axel',
    gender: 'M',
    address: {
      type: 'apt',
      houseNumber: '1000',
      street: '8th Ave',
      city: 'New York',
      state: 'NY',
      zipcode: '10002',
    },
    phoneNumber: '2121239900',
  },
  {
    firstName: 'Allison',
    lastName: 'Bons',
    gender: 'F',
    address: {
      type: 'apt',
      houseNumber: '123',
      street: '5th Ave',
      city: 'Amster',
      state: 'NY',
      zipcode: '10003',
    },
    phoneNumber: '2129089900',
  },
  {
    firstName: 'Bob',
    lastName: 'Charles',
    gender: 'M',
    address: {
      type: 'house',
      houseNumber: '11100',
      street: 'Cherry Lane',
      city: 'Jersey City',
      state: 'NJ',
      zipcode: '07030',
    },
    phoneNumber: '2011234567',
  },
  {
    firstName: 'Maisy',
    lastName: 'Chan',
    gender: 'F',
    address: {
      type: 'apt',
      houseNumber: '1010',
      street: '12th St',
      city: 'Jersey City',
      state: 'NJ',
      zipcode: '07302',
    },
    phoneNumber: '2017654321',
  },
  {
    firstName: 'James',
    lastName: 'Fox',
    gender: 'M',
    address: {
      type: 'house',
      houseNumber: '100-32',
      street: 'Broadway',
      city: 'Weehawken',
      state: 'NJ',
      zipcode: '07086',
    },
    phoneNumber: '20198765432',
  },
  {
    firstName: 'Karl',
    lastName: 'Ito',
    gender: 'M',
    address: {
      type: 'apt',
      houseNumber: '9983',
      street: '40th Rd',
      city: 'Flushing',
      state: 'NY',
      zipcode: '11354',
    },
    phoneNumber: '6469089900',
  },
  {
    firstName: 'Anna',
    lastName: 'Agusto',
    gender: 'F',
    address: {
      type: 'apt',
      houseNumber: '2200',
      street: 'Northern Blvd',
      city: 'Flushing',
      state: 'NY',
      zipcode: '11355',
    },
    phoneNumber: '7182947193',
  },
  {
    firstName: 'Alex',
    lastName: 'Junto',
    gender: 'M',
    address: {
      type: 'house',
      houseNumber: '123',
      street: '5th Ave',
      city: 'Amster',
      state: 'NY',
      zipcode: '10003',
    },
    phoneNumber: '7184212321',
  },
  {
    firstName: 'Maggie',
    lastName: 'Jones',
    gender: 'F',
    address: {
      type: 'apt',
      houseNumber: '70-01',
      street: '70th Rd',
      city: 'Forest Hills',
      state: 'NY',
      zipcode: '11366',
    },
    phoneNumber: '7184561229',
  },
  {
    firstName: 'Charlotte',
    lastName: 'Cibowska',
    gender: 'F',
    address: {
      type: 'apt',
      houseNumber: '6434',
      street: '64th Pl',
      city: 'Brooklyn',
      state: 'NY',
      zipcode: '11217',
    },
    phoneNumber: '7189015555',
  },
  {
    firstName: 'Chad',
    lastName: 'Jenkins',
    gender: 'M',
    address: {
      type: 'house',
      houseNumber: '9090',
      street: 'Forest Lane',
      city: 'Danbury',
      state: 'CT',
      zipcode: '06810',
    },
    phoneNumber: '2038761112',
  },
  {
    firstName: 'Fiona',
    lastName: 'Soo',
    gender: 'F',
    address: {
      type: 'house',
      houseNumber: '909',
      street: 'Oak Lane',
      city: 'Danbury',
      state: 'CT',
      zipcode: '06811',
    },
    phoneNumber: '2031115654',
  },
];

export { mockAddress };